# Generated by Django 3.1.7 on 2021-03-09 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity_donation_app', '0003_auto_20210304_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='pick_uP_time',
            new_name='pick_up_time',
        ),
    ]
